language: python

python:
  - "2.7"

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt

script:
  - PYTHONPATH=. pytest tests -v
after_success: |
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker build -t ynqa/tensorflow-serving-exporter:latest .
    docker push ynqa/tensorflow-serving-exporter:latest
  fi
